-- WoWpoCesku: data pro doplňky Kroniky Azerothu (Kronika.lua)
-- Vzácní mobové podle classic dat (foreverdb.net / CMaNGOS) a novinky WoW Forever: "Jméno|level|t" (t = lovec ochočí)

WoWpoCesku_RareList = {
    ["Durotar"] = { "Geolord Mottle|9", "Warlord Kolkanis|9", "Watch Commander Zalaphil|9", "Captain Flat Tusk|11",
        "Death Flayer|11|t", "Felweaver Scornn|11", "Dustwind Eggtender|5-10", "Shal'ma|?|t" },
    ["Mulgore"] = { "Mazzranache|9|t", "Snagglespear|9", "The Rake|10|t", "Enforcer Emilgund|11", "Sister Hatelash|11",
        "Ghost Howl|12", "Snarlsnout|?", "Stormherald Ukta|?", "Thornstarter Igleg|?" },
    ["The Barrens"] = { "Dishu|13|t", "Rathorian|15", "Elder Mystic Razorsnout|?", "Brokespear|?", "Stonearm|?",
        "Takk the Leaper|19", "Gesharahan|?", "Rocklance|?", "Swiftmane|21", "Trigore the Lasher|19", "Boahn|?",
        "Engineer Whirleygig|?", "Foreman Grills|?", "Humar the Pridelord|23|t", "Sludge Anomaly|?",
        "Lakota'mani|?", "Ishamuhale|?", "Geopriest Gukk'rok|19", "Swinegart Spearhide|22" },
    ["Teldrassil"] = { "Threggil|6", "Uruson|7", "Fury Shelda|8", "Duskstalker|9|t", "Grimmaw|11", "Blackmoss the Fetid|13",
        "Nightscreech|?|t", "Wrathvine|?" },
    ["Zephras Isle"] = { "Den'dralass|?", "Fernfeather|?|t", "Galemender Delanea|?", "Mystmane|?|t", "Slydris|?",
        "Tel'daeor the Stormspeaker|?", "The Lost One|?", "Snapbeak the Quick|3-12" },
    ["Darkshore"] = { "Shadowclaw|13|t", "Licillin|14", "Lord Sinslayer|15", "Carnivous the Breaker|16", "Flagglemurk the Cruel|16",
        "Lady Moongazer|17", "Firecaller Radison|19", "Strider Clutchmother|20|t", "Lady Vespira|22", "Baron Marinous|11-19" },
    ["Ashenvale"] = { "Apothecary Falthis|22", "Lady Vespia|22", "Mist Howler|22|t", "Mugglefin|23", "Branch Snapper|25",
        "Rorgish Jowl|25", "Akkrilus|26", "Eck'alom|27", "Oakpaw|27", "Terrowulf Packlord|31", "Ursol'lok|31|t",
        "Prince Raze|32", "Varo'then's Ghost|48" },
    ["Stonetalon Mountains"] = { "Sister Rathtalon|19", "Taskmaster Whipfang|22", "Foreman Rigger|24", "Pridewing Patriarch|25",
        "Sentinel Amarassan|27", "Sorrow Wing|27", "Sister Riven|28", "Brother Ravenoak|29", "Vengeful Ancient|29", "Nal'taszar|30" },
    ["Thousand Needles"] = { "Gibblesnik|28", "Achellios the Banished|31", "Heartrazor|32", "Vile Sting|35|t",
        "Silithid Ravager|36", "Ironeye the Invincible|37" },
    ["Desolace"] = { "Giggler|34|t", "Accursed Slitherblade|35", "Hissperak|37", "Kaskk|40", "Cursed Centaur|43", "Prince Kellen|33" },
    ["Dustwallow Marsh"] = { "Drogoth the Roamer|37", "Burgle Eye|38", "Dart|38|t", "Ripscale|39|t", "Hayoc|41|t",
        "Oozeworm|42", "The Rot|43", "Lord Angler|44", "Brimgore|45" },
    ["Feralas"] = { "Snarler|42|t", "Old Grizzlegut|43|t", "Gnarl Leafbrother|44", "Diamond Head|45", "Lady Szallah|46",
        "Qirot|47", "Antilus the Soarer|48", "Bloodroar the Stalker|48", "Arash-ethis|49|t" },
    ["Azshara"] = { "The Evalcharr|48", "Gatekeeper Rageroar|49", "Antilos|50", "General Fangferror|50", "Lady Sesspira|51",
        "Magister Hawkhelm|51", "Master Feardred|51", "Scalebeard|52", "Monnos the Elder|53" },
    ["Tanaris"] = { "Murderous Blisterpaw|43|t", "Warleader Krazzilak|45", "Greater Firebird|46|t", "Kregg Keelhaul|47",
        "Haarka the Ravenous|50" },
    ["Un'Goro Crater"] = { "Jin'Zallah the Sandbringer|46", "Cyclok the Mad|48", "Omgorn the Lost|50", "Ravasaur Matriarch|50",
        "Soriid the Devourer|50", "Uhk'loc|52|t", "Clutchmother Zavas|54", "Gruff|57", "King Mosh|60" },
    ["Silithus"] = { "Krellack|56|t", "Gretheer|57|t", "Rex Ashil|57", "Grubthor|58", "Huricanian|58", "Zora|59",
        "Lapress|60", "Twilight Lord Everun|60", "Setis|61" },
    ["Felwood"] = { "Death Howl|49|t", "Mongress|50|t", "Ragepaw|51", "The Ongar|51", "Olm the Wise|52|t",
        "Alshirr Banebreath|54", "Dessecus|56", "Immolatus|56" },
    ["Winterspring"] = { "Mezzir the Howler|55", "General Colbatann|56", "Rak'shiri|57|t", "Azurous|59", "Grizzle Snowpaw|59",
        "Kashoch the Reaver|60", "Lady Hederine|61" },

    ["Elwynn Forest"] = { "Morgaine the Sly|10", "Mother Fang|10|t", "Narg the Taskmaster|10", "Thuros Lightfingers|11",
        "Fedfennel|12", "Gruff Swiftbite|12", "Elmpaw|12" },
    ["Stormwind City"] = { "Sewer Beast|50|t" },
    ["Westfall"] = { "Slark|10", "Vultros|10|t", "Master Digger|11", "Leprithus|12", "Foe Reaper 4000|12",
        "Sergeant Brashclaw|13", "Brack|14" },
    ["Dun Morogh"] = { "Edan the Howler|9", "Timber|10|t", "Gibblewilt|11", "Great Father Arctikus|11", "Bjarn|12|t",
        "Hammerspine|12", "Ghostfang|?|t" },
    ["Tirisfal Glades"] = { "Lost Soul|6", "Farmer Solliden|8", "Tormented Spirit|8", "Bayne|10", "Muad|10",
        "Ressan the Needler|11|t", "Deeb|12", "Fellicent's Shade|12", "Sri'skulk|13|t", "Krethis Shadowspinner|15|t",
        "Blightsculler|?", "Coldrasp|?|t", "Decrepit Harvester|?", "The Condemned One|?" },
    ["Silverpine Forest"] = { "Gorefang|13|t", "Old Vicejaw|14|t", "Dalaran Spellscribe|21", "Ravenclaw Regent|22" },
    ["Hillsbrad Foothills"] = { "Creepthess|24|t", "Ro'Bark|28", "Tamra Stormpike|28", "Scargil|30", "Lady Zephris|33" },
    ["Alterac Mountains"] = { "Rot Hide Bruiser|22", "Jimmy the Bleeder|23", "Snarlmane|23", "Cranky Benj|32|t", "Araga|35|t",
        "Gravis Slipknot|36", "Skhowl|36", "Stone Fury|37", "Lo'Grosh|39", "Narillasanz|44" },
    ["Arathi Highlands"] = { "Big Samras|27|t", "Singer|34", "Kovork|36", "Nimar the Slayer|37", "Darbel Montrose|39",
        "Molok the Crusher|39", "Ruul Onestone|39", "Geomancer Flintdagger|40", "Zalas Witherbark|40", "Foulbelly|42" },
    ["Wetlands"] = { "Ma'ruk Wyrmscale|23", "Gnawbone|24", "Leech Widow|24|t", "Mirelow|25", "Garneg Charskull|29",
        "Dragonmaw Battlemaster|30", "Sludginn|30", "Razormaw Matriarch|31|t", "Prince Nazjak|41", "Nightveiled Rotheap|31-32" },
    ["Loch Modan"] = { "Lord Condar|15|t", "Emogg the Crusher|19", "Shanda the Spinner|19|t", "Magosh|21", "Boss Galgosh|22",
        "Large Loch Crocolisk|22|t" },
    ["Redridge Mountains"] = { "Ribchaser|17", "Snarlflare|18", "Squiddic|19", "Seeker Aqualon|21", "Chatter|23|t",
        "Boulderheart|25", "Rohh the Silent|26", "Kazon|27" },
    ["Duskwood"] = { "Lupos|23|t", "Naraxis|27|t", "Lord Malathrom|31", "Commander Felstrom|32", "Fenros|32", "Nefaru|34" },
    ["Stranglethorn Vale"] = { "Gluggle|37", "Roloch|38", "Kurmokk|42|t", "Verifonix|42", "Mosh'Ogg Butcher|44", "Rippa|44",
        "Lord Sakrasis|45", "Scale Belly|45" },
    ["The Hinterlands"] = { "Old Cliff Jumper|42|t", "Zul'arek Hatefowler|43", "Razortalon|44", "Witherheart the Stalker|45",
        "Retherokk the Berserker|48", "Jalinde Summerdrake|49", "The Reak|49", "Grimungous|50", "Ironback|51|t",
        "Mith'rethis the Enchanter|52" },
    ["Western Plaguelands"] = { "Foulmane|52", "Lord Maldazzar|56", "Foreman Marcrid|58", "Putridius|58", "Scarlet Smith|58",
        "Scarlet Executioner|60", "Scarlet Judge|60", "Scarlet Interrogator|61", "Foreman Jerris|62", "The Husk|62",
        "Scarlet High Clerist|63" },
    ["Eastern Plaguelands"] = { "Duggan Wildhammer|55", "Deathspeaker Selendre|56", "Gish the Unmoving|56", "Hed'mush the Rotting|57",
        "Lord Darkscythe|57", "Warlord Thresh'jin|58", "High General Abbendis|59", "Zul'Brin Warpbranch|59", "Ranger Lord Hawkspear|60" },
    ["Badlands"] = { "War Golem|36", "Broken Tooth|37|t", "Digmaster Shovelphlange|38", "Shadowforge Commander|40",
        "Siege Golem|40", "7:XT|41", "Anathemus|45", "Rumbler|45", "Zaricotl|55|t" },
    ["Searing Gorge"] = { "Faulty War Golem|46", "Shleipnarr|47", "Rekk'tilac|48|t", "Scald|49", "Slave Master Blackheart|50",
        "Smoldar|50", "Highlord Mastrogonde|51" },
    ["Burning Steppes"] = { "The Behemoth|50", "Deathmaw|53|t", "Gorgon'och|54", "Hahk'Zor|54", "Scarshield Quartermaster|55",
        "Terrorspark|55", "Malfunctioning Reaver|56", "Thauris Balgarr|57", "Gruklash|59", "Hematos|60", "Volchan|60" },
    ["Swamp of Sorrows"] = { "Lost One Cook|37", "Lost One Chieftain|39", "Molt Thorn|42", "Fingat|43", "Gilmorian|43",
        "Lord Captain Wyrmak|45", "Jade|47", "Veyzhak the Cannibal|48", "Zekkis|48" },
    ["Blasted Lands"] = { "Mojo the Twisted|48", "Deatheye|49", "Grunter|50|t", "Ravage|51|t", "Akubar the Seer|54",
        "Magronos the Unyielding|56" },
}

-- Místa k objevení (anglické názvy podoblastí, jak je ukazuje hra; dungeon se počítá při vstupu)
WoWpoCesku_Objevy = {
    ["Durotar"] = { "Valley of Trials", "Razor Hill", "Sen'jin Village", "Echo Isles", "Tiragarde Keep", "Skull Rock",
        "Drygulch Ravine", "Thunder Ridge", "Orgrimmar", "Ragefire Chasm" },
    ["Mulgore"] = { "Camp Narache", "Bloodhoof Village", "Thunder Bluff", "Red Rocks", "Bael'dun Digsite", "The Venture Co. Mine",
        "Windfury Ridge", "Palemane Rock", "Stonebull Lake" },
    ["The Barrens"] = { "The Crossroads", "Ratchet", "Camp Taurajo", "Lushwater Oasis", "The Forgotten Pools", "Northwatch Hold",
        "Bael Modan", "Field of Giants", "The Merchant Coast", "Wailing Caverns" },
    ["Teldrassil"] = { "Shadowglen", "Dolanaar", "Darnassus", "Rut'theran Village", "Ban'ethil Barrow Den", "Oracle Glade",
        "Lake Al'Ameth", "Starbreeze Village", "Fel Rock" },
    ["Zephras Isle"] = { "Thendal Grove" },
    ["Darkshore"] = { "Auberdine", "Ameth'Aran", "Bashal'Aran", "Tower of Althalaxx", "Grove of the Ancients", "Cliffspring Falls",
        "Mist's Edge", "Twilight Vale" },
    ["Ashenvale"] = { "Astranaar", "Splintertree Post", "Demon Fall Canyon", "Raynewood Retreat", "Zoram Strand", "Lake Falathim",
        "Satyrnaar", "Warsong Lumber Camp", "Blackfathom Deeps" },
    ["Stonetalon Mountains"] = { "Sun Rock Retreat", "Stonetalon Peak", "Windshear Crag", "The Charred Vale", "Malaka'jin",
        "Talondeep Path", "Mirkfallon Lake" },
    ["Thousand Needles"] = { "Freewind Post", "The Shimmering Flats", "Mirage Raceway", "Highperch", "Splithoof Crag",
        "Darkcloud Pinnacle", "Razorfen Downs" },
    ["Desolace"] = { "Nijel's Point", "Shadowprey Village", "Kodo Graveyard", "Mannoroc Coven", "Thunder Axe Fortress",
        "Gelkis Village", "Magram Village", "Maraudon" },
    ["Dustwallow Marsh"] = { "Theramore Isle", "Brackenwall Village", "Witch Hill", "Shady Rest Inn", "Alcaz Island",
        "Wyrmbog", "Onyxia's Lair" },
    ["Feralas"] = { "Feathermoon Stronghold", "Camp Mojache", "The Twin Colossals", "Dream Bough", "Isle of Dread",
        "Lower Wilds", "Dire Maul" },
    ["Azshara"] = { "Valormok", "Talrendis Point", "Ruins of Eldarath", "Bay of Storms", "Lake Mennar", "Haldarr Encampment",
        "Timbermaw Hold" },
    ["Tanaris"] = { "Gadgetzan", "Steamwheedle Port", "Caverns of Time", "Lost Rigger Cove", "Noxious Lair",
        "Valley of the Watchers", "Zul'Farrak" },
    ["Un'Goro Crater"] = { "Marshal's Refuge", "Fire Plume Ridge", "Golakka Hot Springs", "The Slithering Scar",
        "Lakkari Tar Pits", "Terror Run", "Fungal Rock" },
    ["Silithus"] = { "Cenarion Hold", "The Scarab Wall", "Hive'Ashi", "Hive'Zora", "Hive'Regal", "Southwind Village",
        "Twilight Base Camp" },
    ["Felwood"] = { "Talonbranch Glade", "Bloodvenom Post", "Emerald Sanctuary", "Jaedenar", "Shadow Hold", "Irontree Woods",
        "Bloodvenom Falls" },
    ["Winterspring"] = { "Everlook", "Frostsaber Rock", "Mazthoril", "Darkwhisper Gorge", "Lake Kel'Theril", "Owl Wing Thicket",
        "Winterfall Village" },
    ["Moonglade"] = { "Nighthaven", "Shrine of Remulos", "Stormrage Barrow Dens", "Lake Elune'ara" },

    ["Elwynn Forest"] = { "Northshire Valley", "Goldshire", "Jasperlode Mine", "Fargodeep Mine", "Brackwell Pumpkin Patch",
        "Tower of Azora", "Eastvale Logging Camp", "Stone Cairn Lake", "Crystal Lake" },
    ["Stormwind City"] = { "Trade District", "Mage Quarter", "Old Town", "Dwarven District", "Cathedral Square",
        "Stormwind Keep", "The Canals", "The Stockade" },
    ["Westfall"] = { "Sentinel Hill", "Moonbrook", "Saldean's Farm", "Westfall Lighthouse", "Jangolode Mine", "Gold Coast Quarry",
        "The Dagger Hills", "The Deadmines" },
    ["Dun Morogh"] = { "Coldridge Valley", "Kharanos", "Ironforge", "Brewnall Village", "Amberstill Ranch", "Frostmane Hold",
        "Gnomeregan" },
    ["Tirisfal Glades"] = { "Deathknell", "Brill", "Undercity", "Agamand Mills", "Scarlet Monastery", "The Bulwark",
        "Garren's Haunt", "Brightwater Lake" },
    ["Silverpine Forest"] = { "The Sepulcher", "Pyrewood Village", "Ambermill", "Fenris Isle", "Shadowfang Keep",
        "The Greymane Wall" },
    ["Hillsbrad Foothills"] = { "Southshore", "Tarren Mill", "Durnholde Keep", "Azurelode Mine", "Dun Garok", "Hillsbrad Fields" },
    ["Alterac Mountains"] = { "Ruins of Alterac", "Strahnbrad", "Dalaran", "Ravenholdt Manor", "Crushridge Hold" },
    ["Arathi Highlands"] = { "Refuge Pointe", "Hammerfall", "Stromgarde Keep", "Witherbark Village", "Faldir's Cove",
        "Circle of East Binding", "Circle of West Binding" },
    ["Wetlands"] = { "Menethil Harbor", "Thandol Span", "Dun Modr", "Thelgen Rock", "Whelgar's Excavation Site", "Dragonmaw Gates",
        "Grim Batol" },
    ["Loch Modan"] = { "Thelsamar", "Stonewrought Dam", "Valley of Kings", "Farstrider Lodge", "Ironband's Excavation Site",
        "Mo'grosh Stronghold", "Silver Stream Mine" },
    ["Redridge Mountains"] = { "Lakeshire", "Stonewatch Keep", "Tower of Ilgalar", "Render's Valley", "Alther's Mill",
        "Lake Everstill" },
    ["Duskwood"] = { "Darkshire", "Raven Hill", "Raven Hill Cemetery", "Twilight Grove", "Roland's Doom", "Sven's Camp",
        "Brightwood Grove" },
    ["Stranglethorn Vale"] = { "Booty Bay", "Grom'gol Base Camp", "Rebel Camp", "Nesingwary's Expedition", "Gurubashi Arena",
        "Zul'Gurub", "Mosh'Ogg Ogre Mound", "Jaguero Isle" },
    ["The Hinterlands"] = { "Aerie Peak", "Revantusk Village", "Jintha'Alor", "Shadra'Alor", "Seradane", "Quel'Danil Lodge",
        "The Altar of Zul" },
    ["Western Plaguelands"] = { "Chillwind Camp", "The Bulwark", "Andorhal", "Caer Darrow", "Uther's Tomb", "Hearthglen",
        "Sorrow Hill", "Dalson's Tears" },
    ["Eastern Plaguelands"] = { "Light's Hope Chapel", "Stratholme", "Darrowshire", "Tyr's Hand", "Corin's Crossing",
        "Plaguewood", "Terrordale" },
    ["Badlands"] = { "Kargath", "Uldaman", "Lethlor Ravine", "Angor Fortress", "Camp Kosh", "Dustbelch Grotto" },
    ["Searing Gorge"] = { "Thorium Point", "The Cauldron", "Firewatch Ridge", "Grimesilt Dig Site", "Blackrock Mountain" },
    ["Burning Steppes"] = { "Morgan's Vigil", "Flame Crest", "Dreadmaul Rock", "Ruins of Thaurissan", "Blackrock Stronghold",
        "Blackrock Spire" },
    ["Swamp of Sorrows"] = { "Stonard", "Fallow Sanctuary", "Pool of Tears", "Misty Reed Strand", "Splinterspear Junction",
        "The Temple of Atal'Hakkar" },
    ["Blasted Lands"] = { "Nethergarde Keep", "The Dark Portal", "Dreadmaul Hold", "The Tainted Scar", "Altar of Storms",
        "Serpent's Coil" },
    ["Deadwind Pass"] = { "Karazhan", "Ariden's Camp", "Deadman's Crossing", "Grosh'gok Compound", "Sleeping Gorge" },
}

-- Krátké české poznámky k důležitým postavám (klíč = jméno NPC ve hře)
WoWpoCesku_Postavy = {
    -- Horda
    ["Thrall"] = "Válečný náčelník Hordy, syn Durotana. Vyrůstal jako otrok a gladiátor v Durnholde, utekl, osvobodil orky z táborů a dovedl je na Kalimdor. Šaman, který chce pro svůj lid mír.",
    ["Vol'jin"] = "Vůdce trollů Darkspear. Thrall jeho kmen kdysi zachránil a Vol'jin mu od té doby věrně slouží.",
    ["Cairne Bloodhoof"] = "Náčelník taurenů a moudrý stařešina Thunder Bluff. S Thrallovou pomocí dovedl svůj lid do Mulgore.",
    ["Lady Sylvanas Windrunner"] = "Královna Forsaken. Bývalá generálka hraničářů z Quel'Thalas, kterou Arthas zabil a proměnil v banshee. Touží po pomstě.",
    ["Varimathras"] = "Démon, poradce Sylvanas. Slouží jí, protože musí – ale věrnost démona je vždy podezřelá.",
    ["Master Apothecary Faranell"] = "Vede lékárníky Royal Apothecary Society v Undercity. Jejich „lék“ proti Pohromě je ve skutečnosti nový mor.",
    ["Magatha Grimtotem"] = "Stará šamanka kmene Grimtotem. Cairne ji toleruje, ale ona touží po moci nad tauren.",
    ["Hamuul Runetotem"] = "První tauren druid. Učil se u Malfuriona Stormrage a spojuje taureny s nočními elfy.",
    ["Arch Druid Hamuul Runetotem"] = "První tauren druid. Učil se u Malfuriona Stormrage a spojuje taureny s nočními elfy.",
    ["Nazgrel"] = "Orkský generál, šéf Thrallovy bezpečnosti v Orgrimmaru.",
    ["Eitrigg"] = "Starý ork, kterého kdysi zachránil paladin Tirion Fordring – a za to byl Tirion vyhnán z řádu.",
    ["Rexxar"] = "Napůl ork a napůl ogr, šampion Hordy z Warcraft III. Toulá se po Desolace se svou medvědicí Mishou.",
    ["Mankrik"] = "Ork, který hledá svou ženu Olgru. Hráči ji hledali tak dlouho, že se z toho stal slavný meme.",
    ["Gazlowe"] = "Goblinský šéf Ratchetu. Postavil Thrallovi Orgrimmar – a za pořádnou cenu.",
    ["Neeru Fireblade"] = "Orkský čaroděj v Cleft of Shadow. Tváří se jako přítel, ale stopy vedou ke kultu Burning Blade.",
    ["Zalazane"] = "Šílený čaroděj, který vyhnal trolly Darkspear z Echo Isles a ovládá část jejich lidu.",
    ["Drek'Thar"] = "Slepý šaman klanu Frostwolf, který Thralla naučil šamanismu.",

    -- Aliance
    ["Highlord Bolvar Fordragon"] = "Regent Stormwindu, který vládne za malého krále Anduina. Statečný paladin, který nese tíhu celého království.",
    ["Lady Katrana Prestor"] = "Vlivná šlechtična u dvora. SPOILER: je to černá dračice Onyxia, dcera Deathwinga.",
    ["Anduin Wrynn"] = "Malý král Stormwindu. Jeho otec Varian zmizel na cestě do Theramore.",
    ["King Anduin Wrynn"] = "Malý král Stormwindu. Jeho otec Varian zmizel na cestě do Theramore.",
    ["King Magni Bronzebeard"] = "Král trpaslíků v Ironforge. Jeho bratr Muradin zmizel v Northrendu a Brann putuje po světě.",
    ["High Tinker Mekkatorque"] = "Král gnómů. Gnomeregan ztratil kvůli troggům a zradě svého poradce Thermaplugga.",
    ["Tyrande Whisperwind"] = "Velekněžka Elune a vůdkyně nočních elfů. Bojovala už ve Válce starověku před deseti tisíci lety.",
    ["Arch Druid Fandral Staghelm"] = "Arcidruid, který zasadil Teldrassil. Strom ale nemá požehnání draků – a les choří.",
    ["Lady Jaina Proudmoore"] = "Vládkyně Theramore a mocná čarodějka. Postavila se na stranu míru s Thrallem – i proti vlastnímu otci.",
    ["Master Mathias Shaw"] = "Šéf tajné služby SI:7 ve Stormwindu.",
    ["Gryan Stoutmantle"] = "Velitel Lidové domobrany na Sentinel Hill. Brání Westfall, když Stormwind nepomáhá.",
    ["Marshal Dughan"] = "Velitel stráží v Goldshire. Jeho nástěnka je místo, kde visí plakát na Hoggera.",
    ["Shandris Feathermoon"] = "Generálka strážkyň nočních elfů, velí Feathermoon Stronghold ve Feralas.",
    ["Conservator Ilthalaine"] = "Strážce Shadowglenu, první učitel mladých nočních elfů.",

    -- Padouši a legendy
    ["Hogger"] = "Nejslavnější gnoll Warcraftu, vůdce gnollů Riverpaw v Elwynn Forest. Mnoho hrdinů na něj nestačilo.",
    ["Edwin VanCleef"] = "Vůdce Bratrstva Defias. Kdysi mistr kameníků, kterým šlechta nezaplatila za obnovu Stormwindu.",
    ["Captain Grayson"] = "Duch pirátského kapitána v majáku Westfallu. Jeho loď ztroskotala, když maják nesvítil.",
    ["Old Murk-Eye"] = "Starý vůdce murloků na pobřeží Westfallu, který útočí na maják.",
    ["Stitches"] = "Obří zrůda sešitá z mrtvol nekromantem Abercrombiem v Duskwoodu.",
    ["Morbent Fel"] = "Nekromant, který vládne hřbitovu Raven Hill v Duskwoodu.",
    ["Tirion Fordring"] = "Paladin vyhnaný z řádu za to, že zachránil orka Eitrigga. Dnes žije jako poustevník – jeho příběh ještě neskončil.",
    ["Lord Victor Nefarius"] = "Tajemný lord v Blackrock Spire. SPOILER: je to černý drak Nefarian, syn Deathwinga.",
    ["Ragnaros"] = "Pán ohně, vyvolaný Dark Ironským čarodějem Thaurissanem. Vládne v Molten Core.",
    ["Onyxia"] = "Černá dračice, dcera Deathwinga. Ve Stormwindu se vydává za lady Prestor.",
    ["Kel'Thuzad"] = "Arcimág, zakladatel Kultu zatracených. Po smrti se vrátil jako lich a vládne z Naxxramas.",
    ["Baron Rivendare"] = "Pán nemrtvých ve Stratholme. Z jeho koně Deathcharger se stal sen každého hráče.",
    ["Darkmaster Gandling"] = "Ředitel Scholomance, školy nekromancie pod Caer Darrow.",
    ["Emperor Dagran Thaurissan"] = "Císař Dark Ironů v Blackrock Depths. SPOILER: vzal si princeznu Moiru, dceru krále Magniho.",
    ["Princess Moira Bronzebeard"] = "Dcera krále Magniho. Nechce být „zachráněna“ – je ženou císaře Thaurissana.",
    ["Lord Kazzak"] = "Obří démon v Blasted Lands, který zůstal na Azerothu po zničení Temného portálu.",
    ["Azuregos"] = "Modrý drak v Azshara, ochránce magických artefaktů.",
    ["Hemet Nesingwary Jr."] = "Slavný lovec ve Stranglethorn. Jméno je odkaz na Ernesta Hemingwaye.",
    ["Linken"] = "Podivný „chlapec“ v Un'Goro s mečem a štítem – odkaz na Linka ze Zeldy.",
    ["Keeper Remulos"] = "Syn poloboha Cenaria, strážce Moonglade.",
    ["Highlord Demitrian"] = "Strážce v Silithu, který zná tajemství legendárního meče Thunderfury.",
    ["Anachronos"] = "Bronzový drak v Tanaris, strážce Žezla pohyblivých písků.",
    ["Mr. Smite"] = "Tauren, první důstojník Defias v Deadmines. V boji mění zbraně.",
    ["Cookie"] = "Murlok kuchař lodi Defias v Deadmines.",
    ["Princess"] = "Obrovská prasnice z Brackwell Pumpkin Patch, kterou si přivlastnili Defiasové.",
    ["Maybell Maclure"] = "Dívka z Elwynnu, zamilovaná do Tommyho Joea Stonefielda ze znepřátelené rodiny.",

    -- Zephras Isle (WoW Forever)
    ["Rorian the Dayseeker"] = "Vůdce Thendal Grove, který vede mladé shen'dorei.",
    ["Aetheen of the Gales"] = "Členka Rady starších, přišla číst proudění větrů a posoudit, kdo je připraven sloužit ostrovu.",
    ["Halaan Hawk-Eye"] = "Hraničář, který ti půjčí svůj dar a ukáže kotevní pylon v dálce.",
    ["Myriaal"] = "Shen'dorei z Thendal Grove. Dává „bonusové body“ tomu, kdo vyleká Roriana skokem z věže.",
}

-- Novinky WoW Forever (nejsou v classic datech): souřadnice na mapě oblasti v procentech (foreverchanges.pro)
WoWpoCesku_RareMapPts = {
    ["Elmpaw"] = { "Elwynn Forest", 81.6, 85.4, 75, 38.4 },
    ["Ghostfang"] = { "Dun Morogh", 74.2, 63.2 },
    ["Baron Marinous"] = { "Darkshore", 59.2, 22.6 },
    ["Dustwind Eggtender"] = { "Durotar", 51.2, 20.6, 52.2, 24 },
    ["Shal'ma"] = { "Durotar", 59.8, 91 },
    ["Nightscreech"] = { "Teldrassil", 46.4, 33.6 },
    ["Wrathvine"] = { "Teldrassil", 53.4, 70.4 },
    ["Den'dralass"] = { "Zephras Isle", 61.2, 37.2, 56.3, 31.7 },
    ["Fernfeather"] = { "Zephras Isle", 48, 85.4, 53.8, 78.8 },
    ["Galemender Delanea"] = { "Zephras Isle", 62.4, 62 },
    ["Mystmane"] = { "Zephras Isle", 60.2, 34.6 },
    ["Slydris"] = { "Zephras Isle", 50.2, 51 },
    ["Tel'daeor the Stormspeaker"] = { "Zephras Isle", 66, 53.8 },
    ["The Lost One"] = { "Zephras Isle", 52, 46.4 },
}
