-- © 2026 RankonRP a přispěvatelé. Překlady a texty nelze kopírovat do jiných addonů ani projektů bez povolení – viz docs/LICENSE-DATA.md
-- WoWpoCesku: krátký popis míst z Poutníkova deníku, která nemají tip v záložce Tajemství (zobrazí se na mapě pod popiskem).
-- Podle klasického WoW a Warcraft Wiki; ve WoW Forever se může něco lišit.
WoWpoCesku_MistaPopis = {
    ["Durotar"] = {
        ["Valley of Trials"] = "Startovní údolí orků a trollů; tady začínají noví hráči Hordy.",
        ["Razor Hill"] = "Hlavní osada Durotaru s hordskými trenéry, hostincem a letištěm.",
        ["Sen'jin Village"] = "Vesnice trollů z kmene Darkspear, pojmenovaná po vůdci Sen'jinovi, který zahynul při cestě Hordy do Kalimdoru.",
        ["Echo Isles"] = "Ostrovy u pobřeží, původní domov trollů Darkspear. Ovládl je čaroděj Zalazane, než je Horda osvobodila.",
        ["Tiragarde Keep"] = "Pevnost lidí z Kul Tiras na pobřeží Durotaru, připomínka Proudmooreova tažení proti Hordě.",
        ["Skull Rock"] = "Skalní útes ve tvaru lebky ve vnitrozemí Durotaru.",
        ["Drygulch Ravine"] = "Suchá rokle ve východním Durotaru.",
        ["Thunder Ridge"] = "Skalní hřeben v severním Durotaru.",
        ["Orgrimmar"] = "Hlavní město Hordy. Thrall ho postavil a pojmenoval po Orgrimovi Doomhammerovi.",
        ["Ragefire Chasm"] = "Sopečný dungeon pod Orgrimmarem, kde sídlí kult Burning Blade a ohniví tvorové.",
    },
    ["Mulgore"] = {
        ["Camp Narache"] = "Startovní tábor taurenů; odsud vyrážejí noví hráči Hordy z řad taurenů.",
        ["Bloodhoof Village"] = "Vesnice taurenů, domov klanu Bloodhoof. Žije tu rodina vůdce Cairna.",
        ["Thunder Bluff"] = "Hlavní město taurenů na plošinách nad Mulgore. Založil ho Cairne Bloodhoof.",
        ["Red Rocks"] = "Červené skály na severu Mulgore.",
        ["Bael'dun Digsite"] = "Archeologické naleziště v Mulgore.",
        ["The Venture Co. Mine"] = "Důl goblinské Venture Company, která ničí krajinu těžbou.",
        ["Windfury Ridge"] = "Hřeben na západě Mulgore, hnízdo harpyjí z kmene Windfury.",
        ["Palemane Rock"] = "Skála na severu Mulgore, kde sídlí gnollové Palemane.",
        ["Stonebull Lake"] = "Jezero ve středu Mulgore.",
    },
    ["The Barrens"] = {
        ["The Crossroads"] = "Hordská pevnost na křižovatce hlavních cest; centrum Barrens.",
        ["Camp Taurajo"] = "Taurenský tábor u hranic Mulgore, brána do jižních Barrens.",
        ["The Forgotten Pools"] = "Jezírka uprostřed Barrens.",
        ["Northwatch Hold"] = "Opevněný tábor Aliance v Barrens.",
        ["Bael Modan"] = "Trpasličí těžební tábor v jižních Barrens.",
        ["The Merchant Coast"] = "Pobřeží v jižních Barrens, kde obchodují goblini.",
        ["Razorfen Kraul"] = "Dungeon kančích lidí z kmene Razorfen s trnitým labyrintem.",
        ["Razorfen Downs"] = "Dungeon na jihu Barrens, kde vládne lich Amnennar the Coldbringer.",
    },
    ["Teldrassil"] = {
        ["Shadowglen"] = "Startovní údolí nočních elfů; noví hráči tu začínají cestu pod stromem Teldrassil.",
        ["Dolanaar"] = "Největší vesnice Teldrassilu, odkud noční elfové spravují okolí.",
        ["Darnassus"] = "Hlavní město nočních elfů ve větvích stromu Teldrassil.",
        ["Rut'theran Village"] = "Přístav na úpatí Teldrassilu s lodí do Auberdine a portálem do Darnassu.",
        ["Ban'ethil Barrow Den"] = "Podzemní doupě nočních elfů, v němž se druidové ukládali ke spánku.",
        ["Oracle Glade"] = "Mýtina s věštkyní, kam míří dobrodruzi z vyšších úrovní.",
        ["Lake Al'Ameth"] = "Jezero ve středu Teldrassilu s ostrůvkem.",
        ["Starbreeze Village"] = "Vesnice v severním Teldrassilu.",
        ["Fel Rock"] = "Skalní jeskyně v Teldrassilu.",
    },
    ["Zephras Isle"] = {
        ["Thendal Grove"] = "Háj na ostrově Zephras Isle; nové místo ve WoW Forever.",
    },
    ["Darkshore"] = {
        ["Bashal'Aran"] = "Zničené město nočních elfů; za Velkého rozpoltění se zřítilo do moře a v ruinách bloudí duchové Highborne.",
        ["Mist's Edge"] = "Útes v severní části Darkshore.",
        ["Twilight Vale"] = "Údolí v Darkshore, kde se zabydleli kultisté.",
    },
    ["Ashenvale"] = {
        ["Astranaar"] = "Hlavní osada Aliance v Ashenvale, odkud noční elfové řídí obranu lesa.",
        ["Splintertree Post"] = "Hordská základna na východě Ashenvale, odkud orkové kácejí les.",
        ["Lake Falathim"] = "Jezero na jihu Ashenvale.",
        ["Satyrnaar"] = "Satyrská tvrz v severním Ashenvale, ruina zlého původu.",
        ["Warsong Lumber Camp"] = "Hordský tábor klanu Warsong s kácením lesa; kvůli němu padl Cenarius.",
    },
    ["Stonetalon Mountains"] = {
        ["Sun Rock Retreat"] = "Taurenská osada ve skalách, základna Hordy v pohoří.",
        ["The Charred Vale"] = "Spálené údolí, které zničili goblini z Venture Company a požáry.",
        ["Mirkfallon Lake"] = "Jezero v Greatwood Vale ve východním Stonetalonu.",
    },
    ["Thousand Needles"] = {
        ["The Shimmering Flats"] = "Solná pláň po vyschlém jezeře; závodiště gnómů a goblinů.",
        ["Splithoof Crag"] = "Skalní útvar v Thousand Needles, kde sídlí kentauři.",
        ["Darkcloud Pinnacle"] = "Skalní věž v Thousand Needles.",
    },
    ["Desolace"] = {
        ["Nijel's Point"] = "Alianční tábor v západním Desolace, který brání před kentaury.",
        ["Shadowprey Village"] = "Hordská rybářská vesnice na pobřeží Desolace.",
        ["Thunder Axe Fortress"] = "Pevnost Aliance na severu Desolace.",
        ["Gelkis Village"] = "Vesnice kentaurů z kmene Gelkis na jihozápadě Desolace.",
        ["Magram Village"] = "Vesnice kentaurů z kmene Magram na jihovýchodě Desolace.",
    },
    ["Dustwallow Marsh"] = {
        ["Theramore Isle"] = "Město Aliance, které založila Jaina Proudmoore, na ostrově v Dustwallow Marsh.",
        ["Brackenwall Village"] = "Vesnice ogrů z kmene Stonemaul v Dustwallow Marsh.",
        ["Wyrmbog"] = "Bažina, kde sídlí Onyxia a její drakové.",
    },
    ["Feralas"] = {
        ["Camp Mojache"] = "Hlavní osada Hordy ve Feralasu, domov taurenů.",
        ["The Twin Colossals"] = "Dvě obří skalní věže, které vznikly při Velkém rozpoltění.",
        ["Lower Wilds"] = "Jižní část Feralasu s prastarými ruinami.",
    },
    ["Azshara"] = {
        ["Valormok"] = "Hordská základna v Azshaře na pobřeží.",
        ["Talrendis Point"] = "Alianční základna v Azshaře, kde noční elfové bdí nad pobřežím.",
        ["Lake Mennar"] = "Jezero v Azshaře, kde se kdysi učili Highborne z akademie Mennar.",
        ["Haldarr Encampment"] = "Tábor satyrů a démonů v Azshaře.",
        ["Temple of Zin-Malor"] = "Ruiny chrámu, kde Highborne ukradli krystal Zin-Malor, který je proklel.",
    },
    ["Tanaris"] = {
        ["Gadgetzan"] = "Hlavní město goblinů v Tanaris a neutrální obchodní centrum.",
        ["Steamwheedle Port"] = "Goblinský přístav v Tanaris, kde obchoduje kartel Steamwheedle.",
        ["Lost Rigger Cove"] = "Zátoka na jihozápadě Tanaris, kde se skrývají piráti Southsea.",
        ["Noxious Lair"] = "Jeskynní doupě silithidů v poušti.",
        ["Valley of the Watchers"] = "Údolí, kde bronzoví draci hlídají čas a doupě Caverns of Time.",
    },
    ["Un'Goro Crater"] = {
        ["Fire Plume Ridge"] = "Sopečný hřeben uprostřed kráteru, kde sídlí ohniví elementálové.",
        ["Golakka Hot Springs"] = "Horké prameny v severním Un'Goro, doupě gorili.",
        ["The Slithering Scar"] = "Jizva v kráteru, kde se usadili silithidi.",
        ["Lakkari Tar Pits"] = "Dehtové jámy v Un'Goro Crater.",
        ["Terror Run"] = "Území elitních dinosaurů, nebezpečné i pro zkušené hrdiny.",
        ["Fungal Rock"] = "Jeskyně uprostřed kráteru plná obřích hub.",
    },
    ["Silithus"] = {
        ["Cenarion Hold"] = "Neutrální středisko Cenarion Circle, které sleduje silithidy a Qiraji.",
        ["The Scarab Wall"] = "Obří zeď, která uzavřela říši Qiraji po Válce pohyblivých písků.",
        ["Southwind Village"] = "Zničená vesnice nočních elfů v Silithusu.",
        ["Twilight Base Camp"] = "Tábor kultu Twilight's Hammer, který v poušti hledá krystaly.",
    },
    ["Felwood"] = {
        ["Talonbranch Glade"] = "Alianční základna ve Felwoodu, odkud se bojuje se zkázou lesa.",
        ["Bloodvenom Post"] = "Dřívější hordská osada ve Felwoodu, kterou zničily zkažené slizy.",
        ["Irontree Woods"] = "Zkažená část Felwoodu.",
        ["Bloodvenom Falls"] = "Jedovatý vodopád ve Felwoodu, kde se zbarvila voda do zelena.",
    },
    ["Winterspring"] = {
        ["Owl Wing Thicket"] = "Houština ve východním Winterspringu.",
        ["Winterfall Village"] = "Vesnice zkažených furbolgů z kmene Winterfall.",
    },
    ["Moonglade"] = {
        ["Nighthaven"] = "Hlavní osada v Moonglade, kde druidové všech ras žijí v míru.",
    },
    ["Elwynn Forest"] = {
        ["Northshire Valley"] = "Startovní údolí lidí s opatstvím Northshire Abbey.",
        ["Goldshire"] = "Vesnice u hlavní cesty v Elwynn Forest se slavným hostincem Lion's Pride.",
        ["Jasperlode Mine"] = "Důl na východě Elwynn Forest, kde se zabydleli kobolti.",
        ["Fargodeep Mine"] = "Důl na jihu Elwynn Forest, kde sídlí kobolti.",
        ["Brackwell Pumpkin Patch"] = "Dýňové pole na jihu Elwynn Forest.",
        ["Tower of Azora"] = "Věž v Elwynn Forest, kde sídlí mág.",
        ["Eastvale Logging Camp"] = "Dřevorubecký tábor na východě Elwynn Forest.",
        ["Stone Cairn Lake"] = "Jezero na jihu Elwynn Forest, kde se rybaří.",
        ["Crystal Lake"] = "Jezero v Elwynn Forest.",
    },
    ["Stormwind City"] = {
        ["Trade District"] = "Obchodní čtvrť Stormwindu s trhem a hostinci.",
        ["Mage Quarter"] = "Čtvrť mágů s Wizard's Sanctum a portály do dalších měst.",
        ["Old Town"] = "Stará čtvrť Stormwindu s hospodami a tmavými uličkami.",
        ["Dwarven District"] = "Trpasličí čtvrť Stormwindu.",
        ["Cathedral Square"] = "Náměstí s katedrálou Světla, sídlo paladinů a kněží.",
        ["Stormwind Keep"] = "Královský hrad Stormwindu, kde sídlí král a jeho rádci.",
        ["The Canals"] = "Kanály a mosty Stormwindu s přístavem.",
        ["The Stockade"] = "Stormwindská věznice, dnes dungeon plný uprchlých vězňů.",
    },
    ["Westfall"] = {
        ["Sentinel Hill"] = "Hlavní osada Westfallu s věží, kde se dobrodruzi vzdorují Defias.",
        ["Moonbrook"] = "Vesnice na východě Westfallu, základna Defias.",
        ["Saldean's Farm"] = "Farma ve Westfallu.",
        ["Westfall Lighthouse"] = "Maják na pobřeží Westfallu, jehož strážce zmizel.",
        ["Jangolode Mine"] = "Důl ve Westfallu.",
        ["Gold Coast Quarry"] = "Lom na pobřeží Westfallu.",
        ["The Dagger Hills"] = "Pahorky na jihu Westfallu.",
        ["The Deadmines"] = "Dungeon pod vesnicí Moonbrook, základna bratrstva Defias.",
    },
    ["Dun Morogh"] = {
        ["Coldridge Valley"] = "Startovní údolí trpaslíků a gnómů.",
        ["Kharanos"] = "Hlavní osada Dun Morogh se slavným pivovarem Thunderbrew.",
        ["Ironforge"] = "Hlavní město trpaslíků v horách Dun Morogh.",
        ["Brewnall Village"] = "Trpasličí vesnice v Dun Morogh.",
        ["Amberstill Ranch"] = "Farma v Dun Morogh.",
        ["Frostmane Hold"] = "Jeskyně ledových trollů z kmene Frostmane.",
        ["Gnomeregan"] = "Gnómské hlavní město a dungeon; po zradě Mekgineera Thermaplugga ho zamořila radiace.",
    },
    ["Tirisfal Glades"] = {
        ["Deathknell"] = "Startovní osada Forsaken s hřbitovem a chrámem.",
        ["Garren's Haunt"] = "Zchátralý statek v Tirisfal Glades, který straší.",
        ["Brightwater Lake"] = "Jezero v jižním Tirisfal Glades.",
    },
    ["Silverpine Forest"] = {
        ["The Greymane Wall"] = "Obří zeď království Gilneas, která oddělila zemi od světa.",
    },
    ["Hillsbrad Foothills"] = {
        ["Hillsbrad Fields"] = "Pole na jihu Hillsbrad Foothills.",
    },
    ["Alterac Mountains"] = {
        ["Crushridge Hold"] = "Pevnost ogrů z kmene Crushridge v ruinách Alteracu.",
    },
    ["Arathi Highlands"] = {
        ["Refuge Pointe"] = "Alianční tábor v Arathi Highlands, základna proti Stromgardu.",
        ["Hammerfall"] = "Hordská základna na východě Arathi Highlands; zde padl Orgrim Doomhammer.",
        ["Stromgarde Keep"] = "Zničená pevnost nejstaršího lidského království Stromgarde.",
        ["Circle of East Binding"] = "Kamenný kruh na kopci v Arathi Highlands, jeden z kruhů, které poutají mocné zlé bytosti.",
        ["Circle of West Binding"] = "Kamenný kruh na kopci v Arathi Highlands, jeden z kruhů, které poutají mocné zlé bytosti.",
    },
    ["Wetlands"] = {
        ["Dun Modr"] = "Trpasličí pevnost nad bažinami, hlídá cestu mezi Khaz Modanem a Wetlands.",
        ["Whelgar's Excavation Site"] = "Archeologické naleziště v Wetlands, které vede trpaslík Whelgar.",
        ["Dragonmaw Gates"] = "Brána před pevností klanu Dragonmaw v Wetlands.",
    },
    ["Loch Modan"] = {
        ["Thelsamar"] = "Hlavní vesnice Loch Modan, základna trpaslíků na břehu jezera.",
        ["Silver Stream Mine"] = "Stříbrný důl v Loch Modan, který ohrožují trogové.",
    },
    ["Redridge Mountains"] = {
        ["Lake Everstill"] = "Jezero ve středu Redridge Mountains.",
    },
    ["Duskwood"] = {
        ["Raven Hill Cemetery"] = "Strašidelný hřbitov v Duskwoodu, kde bloudí mrtví.",
        ["Sven's Camp"] = "Zchátralý tábor v Duskwoodu.",
        ["Brightwood Grove"] = "Háj v Duskwoodu.",
    },
    ["Stranglethorn Vale"] = {
        ["Grom'gol Base Camp"] = "Hordská základna v džungli Stranglethorn.",
        ["Rebel Camp"] = "Tábor lidských vzbouřenců v severním Stranglethornu.",
        ["Nesingwary's Expedition"] = "Lovecký tábor Hemeta Nesingwaryho, který loví nejnebezpečnější zvěř džungle.",
        ["Mosh'Ogg Ogre Mound"] = "Pahorek ogrů z kmene Mosh'Ogg v jižním Stranglethornu.",
        ["Jaguero Isle"] = "Ostrov u pobřeží Stranglethornu.",
    },
    ["The Hinterlands"] = {
        ["Revantusk Village"] = "Vesnice trollů z kmene Revantusk, spojenců Hordy, v Hinterlands.",
        ["Shadra'Alor"] = "Trollí ruiny v jihozápadním Hinterlands.",
        ["The Altar of Zul"] = "Trollský oltář na severu Hinterlands.",
    },
    ["Western Plaguelands"] = {
        ["Chillwind Camp"] = "Alianční tábor ve Western Plaguelands, základna proti Scourge.",
        ["The Bulwark"] = "Hordská pevnost, která brání Tirisfal před Plaguelands.",
        ["Hearthglen"] = "Pevnost Šarlatového řádu na severu Western Plaguelands.",
        ["Sorrow Hill"] = "Kopec s hrobem Uthera Lightbringera, jedním z klidných míst kraje.",
    },
    ["Eastern Plaguelands"] = {
        ["Tyr's Hand"] = "Opevněné město Šarlatového řádu na východě Plaguelands.",
        ["Corin's Crossing"] = "Hradba Aliance proti Scourge ve východním cípu Plaguelands.",
        ["Plaguewood"] = "Zkažený les, kde se plazí mor.",
        ["Terrordale"] = "Zamořené údolí, kde sídlí zvláště hrůzostrašní nemrtví.",
    },
    ["Badlands"] = {
        ["Angor Fortress"] = "Opevněná pevnost v severním Badlands.",
        ["Camp Kosh"] = "Tábor ogrů v Badlands.",
        ["Dustbelch Grotto"] = "Jeskyně ogrů z kmene Dustbelch.",
    },
    ["Searing Gorge"] = {
        ["Firewatch Ridge"] = "Hřeben v Searing Gorge.",
        ["Grimesilt Dig Site"] = "Naleziště trpaslíků v Searing Gorge.",
    },
    ["Burning Steppes"] = {
        ["Flame Crest"] = "Hordský tábor v Burning Steppes.",
        ["Blackrock Stronghold"] = "Pevnost klanu Blackrock v Burning Steppes.",
    },
    ["Swamp of Sorrows"] = {
        ["Pool of Tears"] = "Jezírko uprostřed Swamp of Sorrows.",
        ["Misty Reed Strand"] = "Pobřeží Swamp of Sorrows.",
        ["Splinterspear Junction"] = "Křižovatka v Swamp of Sorrows.",
        ["The Temple of Atal'Hakkar"] = "Potopený chrám trollů Atal'ai, dnes dungeon Sunken Temple.",
    },
    ["Blasted Lands"] = {
        ["The Dark Portal"] = "Brána, kterou orkové vtrhli z Draenoru. Dnes ji hlídá Nethergarde Keep.",
        ["Serpent's Coil"] = "Okruží pustých jezer a hadích bytostí.",
    },
    ["Deadwind Pass"] = {
        ["Sleeping Gorge"] = "Rokle v Deadwind Pass, nedaleko Karazhanu.",
    },
}
